print ("PLease Enter your full name in space provided belowand press enter:")
name = str(input())
print ("Please Enter Your Corect Age Below in years and press enter:")
A = int(input())
print ("Please enter your sex in sapce provided below male/female ? and press enter")
B = str(input())
print ("Please enter your full Address including house number, street, City and State in space provided below")
C = input()
print ("Please enter your pincode in space provided belowand press enter:")
D = int(input())
print ("Please enter your profession below and press enter:")
E = str(input())
print ("Full Name:", name)
print (type (name))
print ("Age:", A,"years")
print (type(A))
print ("SEX:", B)
print (type (B))
print ("Address:", C)
print (type (C))
print ("Pincode:", D)
print (type(D))
print ("Proffesion:", E)
print (type(E))